export const COLORS = {
    FONT_COLOR_MAIN: 'text-slate-900',
    FONT_COLOR_LIGHT: 'text-slate-50',
    FONT_COLOR_DIM: 'text-slate-400',
    FONT_COLOR_HOVER: 'text-slate-600',
    MAIN_BG_COLOR: 'bg-slate-50',
    SIDEBAR_BG_COLOR: 'bg-slate-200',
    NAVBAR_BG_COLOR: 'bg-slate-800',
    BORDER_COLOR: 'border-gray-300',
    HOVER_BG_COLOR: 'hover:bg-gray-300',
    HOVER_TEXT_COLOR: 'hover:text-gray-800',
    FOCUS_OUTLINE: 'focus:outline-none',
    FOCUS_BORDER_COLOR: 'focus:border-gray-500',
    FOCUS_RING: 'focus:ring',
    FOCUS_RING_COLOR: 'focus:ring-gray-300',
    FOCUS_RING_OPACITY: 'focus:ring-opacity-50',
    AR_BUTTON_BG: 'bg-slate-50',
    AR_BUTTON_BG_HOVER: 'hover:bg-slate-100',
  };
  